//
//  BoardSpecTests.swift
//  AvalonCommon
//
//  Created by Ibrahim Sha'ath on 10/30/24.
//

import Testing
@testable import AvalonCommon

struct BoardSpecTests {

    private func draw(_ boardSpec: BoardSpec) -> String {
        var diagram = String()
        for y in Square.Constants.yRange {
            for x in Square.Constants.xRange {
                let square = Square(x: x, y: y)!
                if (boardSpec.obstructedSquares.contains(square)) {
                    diagram.append("X")
                } else if (boardSpec.trapdoorSquares.contains(square)) {
                    diagram.append("T")
                } else {
                    diagram.append(".")
                }
            }
            if y != Square.Constants.yRange.upperBound {
                diagram.append("\n")
            }
        }
        return diagram
    }

    @Test func season1Board1() async throws {
        #expect(
            draw(.season1Board1) == """
            ...........
            ...........
            ...........
            .XX.....XX.
            .XX.....XX.
            ...........
            ...........
            .....T.....
            ...........
            ...........
            .XX.....XX.
            .XX.....XX.
            ...........
            ...........
            ...........
            """
        )
    }

    @Test func season1Board2() async throws {
        #expect(
            draw(.season1Board2) == """
            ...........
            ...........
            ...........
            ...........
            ....XXX....
            ....XXX....
            ...........
            .T.......T.
            ...........
            ....XXX....
            ....XXX....
            ...........
            ...........
            ...........
            ...........
            """
        )
    }

    @Test func season2Board1() async throws {
        #expect(
            draw(.season2Board1) == """
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            .XX.....XX.
            .XX..T..XX.
            .XX.....XX.
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            """
        )
    }

    @Test func season2Board2() async throws {
        #expect(
            draw(.season2Board2) == """
            ...........
            ...........
            .....XX....
            .....XX....
            ...........
            ...........
            .XX...T....
            .XX.....XX.
            ....T...XX.
            ...........
            ...........
            ....XX.....
            ....XX.....
            ...........
            ...........
            """
        )
    }

    @Test func season3Board1() async throws {
        #expect(
            draw(.season3Board1) == """
            ...........
            ...........
            ...X...X...
            ...........
            ...........
            ..X.....X..
            ...........
            .....T.....
            ...........
            ..X.....X..
            ...........
            ...........
            ...X...X...
            ...........
            ...........
            """
        )
    }

    @Test func season3Board2() async throws {
        #expect(
            draw(.season3Board2) == """
            ...........
            ...........
            ....XXX....
            ...........
            ...........
            .....T.....
            ...........
            .XX.....XX.
            ...........
            .....T.....
            ...........
            ...........
            ....XXX....
            ...........
            ...........
            """
        )
    }

    @Test func season4Board1() async throws {
        #expect(
            draw(.season4Board1) == """
            ...........
            ...........
            ...........
            ..XX...XX..
            ..XX...XX..
            ...........
            ...........
            .....T.....
            ...........
            ...........
            ..XX...XX..
            ..XX...XX..
            ...........
            ...........
            ...........
            """
        )
    }

    @Test func season4Board2() async throws {
        #expect(
            draw(.season4Board2) == """
            ...........
            ...........
            .....X.....
            ...........
            ..XX...XX..
            ...........
            ...........
            ..T..X..T..
            ...........
            ...........
            ..XX...XX..
            ...........
            .....X.....
            ...........
            ...........
            """
        )
    }
}
